### ISSUE TITLE
2.1引擎不行

### ISSUE THREAD

**Issue by sdfasffsdf** [ICrazyMouse/Cocos-Shader-Poker#1]

**Comment by Malonrio** [comment]
1.9.x的版本，
2.x的版本API已经变了
[forum.cocos.com](https://forum.cocos.com/)论坛里有2.x的Shader使用

**Comment by sdfasffsdf** [comment]
我找了下 论坛 没有找到，方便贴下 2.x的链接吗？

**Comment by Malonrio** [comment]
你看这个帖子吧，2.x我还没试过：[地址](https://forum.cocos.com/t/cocos-creator-2-x-shader/69098)

**Comment by sdfasffsdf** [comment]
这个 好像是这个工具类
